// src/resources/js/components/auth/login.vue
<template>
    <form autocomplete="off" @submit.prevent="login" method="post">
        <div class="lg:w-2/6 md:w-1/2 bg-gray-200 rounded-lg p-8 flex flex-col md:ml-auto w-full mt-10 md:mt-0">
            <h2 class="text-gray-900 text-lg font-medium title-font mb-5">Sign Up</h2>
            <div class="relative mb-4">
                <label for="email" class="leading-7 text-sm text-gray-600">Email</label>
                <input type="email" id="email" name="email"
                       placeholder="Elektron poçt" v-model="email"
                       class="py-1 px-3 w-full border block">
            </div>
            <div class="relative mb-4">
                <label for="full-name" class="leading-7 text-sm text-gray-600">Full Name</label>
                <input type="text" id="full-name" name="full-name"
                       placeholder="Şifrə" v-model="password"
                       class="w-full bg-white rounded border border-gray-300 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
            </div>
            <button
                class="text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg">
                Button
            </button>
            <p class="text-xs text-gray-500 mt-3">Literally you probably haven't heard of them jean shorts.</p>
        </div>
        <div class="error" v-if="error">
            <h6 class="error__text">{{ error_text }}</h6>
        </div>
        <div class="intro-y box px-5 py-8 mt-8">
            <div class="intro-y">
                <input type="text" class="intro-y auth__input input input--lg w-full border block"
                       placeholder="Elektron poçt" v-model="email">
                <input type="password" class="intro-y auth__input input input--lg w-full border block mt-4"
                       placeholder="Şifrə" v-model="password">
            </div>
            <div class="intro-y auth__info flex text-xs sm:text-sm mt-4">
                <div class="flex items-center mr-auto">
                    <input type="checkbox" class="input border mr-2" id="remember-me">
                    <label class="cursor-pointer select-none" for="remember-me">Remember me</label>
                </div>
                <a href="">Şifrəni sıfırla</a>
            </div>
            <div class="intro-y mt-5 xl:mt-8 text-center xl:text-left">
                <button class="intro-y button button--lg button--primary w-full xl:mr-3">Daxil ol</button>
                <button class="intro-y button button--lg button--secondary w-full border mt-3">Qeydiyyatdan keçmək
                </button>
            </div>
        </div>
    </form>
    <!--            <div class="login__form">-->
    <!--                <input aria-invalid="true" autocomplete="username" id="email" name="email" placeholder="Elektron poçt"-->
    <!--                       type="text" inputmode="text" class="auth__input input input&#45;&#45;lg w-full border block" aria-label="Elektron poçt"-->
    <!--                       autocorrect="off" autocapitalize="none"-->
    <!--                       spellcheck="false"-->
    <!--                       value="" v-model="email">-->
    <!--            </div>-->
    <!--            <div class="login__form">-->
    <!--                <input aria-invalid="true" autocomplete="current-password" id="password" name="password"-->
    <!--                       placeholder="Şifrə"-->
    <!--                       type="password" inputmode="text" class="login__form-input" aria-label="Şifrə"-->
    <!--                       autocorrect="off" autocapitalize="none"-->
    <!--                       spellcheck="false"-->
    <!--                       value="" v-model="password">-->
    <!--            </div>-->
    <!--            <button v-if="loading" class="btn btn-primary login-button"><i class="mdi mdi-spin mdi-loading"/></button>-->
    <!--            <button v-else type="submit" class="btn btn-primary login-button">Daxil ol</button>-->

    <!--            <footer class="login__footer-links">-->
    <!--                <a class="footer__link" data-content-type="requestPasswordForm"-->
    <!--                   href="/">-->
    <!--                    Şifrəni sıfırla-->
    <!--                </a>-->
    <!--                <a href="/" class="footer__link js-change-content"-->
    <!--                   data-content-type="registerForm">-->
    <!--                    Qeydiyyatdan keçmək-->
    <!--                </a>-->
    <!--            </footer>-->

</template>
<script>
export default {
    data() {
        return {
            email: null,
            password: null,
            error: false,
            loading: false,
            error_text: ''
        }
    },
    methods: {
        login() {
            this.loading = true
            axios.post('/api/auth/login', {
                email: this.email,
                password: this.password
            }).then(response => {
                this.loading = false
                if (response.data.success === false) {
                    this.error_text = response.data.error
                    this.error = true
                } else if (response.data.success === true) {
                    window.location = '/';
                }
            })
        },
    }
}
</script>

// front/src/app/components/pages/login.tsx
import React, { useState } from 'react';
import { Link } from 'react-router-dom';

const Login: React.FunctionComponent = () => {
    const [email, setEmail] = useState("");
    const [password, setPassword] = useState("");
    const loading: Boolean = false;
    const [type, setType] = useState("password");

    const handleSubmit = (event: React.FormEvent) => {
        event.preventDefault()
    }

    const changeEmailHandler = (event: React.ChangeEvent<HTMLInputElement>) => {
        setEmail(event.target.value);
    }

    const changePasswordHandler = (event: React.ChangeEvent<HTMLInputElement>) => {
        setPassword(event.target.value);
    }

    return(
        <div className="xs:pt-20 text-center absolute top-1/2 left-1/2 -mr-1/2" style={{transform: "translate(-50%, -50%)"}}>
            <Link to="/" className="text-black font-bold hover:text-gray-200 md:text-2xl m-auto">
                <img
                src="images/DevHub_Monochrome_Full_Logo.svg"
                alt="DevHub Logo"
                width="188"
                height="36"
                className="mb-10 mx-auto" />
            </Link>

            <form autoComplete="off" method="post" className="xs:max-w-xs w-96" onSubmit={handleSubmit}>
                <a
                href="/login/github"
                id="trans-none"
                className="btn-outline border-gray-300 dark:border-gray-300 w-full items-center dark:text-black">
                    <div className="mx-auto flex space-x-1">
                        <span className="iconify text-base text-gray-700" data-icon="simple-icons:github" data-inline="true"></span>
                    </div>
                </a>
                <div className="my-4 items-center flex">
                    <div className="mr-3 flex-grow border-t border-gray-300" aria-hidden="true"></div>
                    <div className="text-sm">{/*{ $t('devhub.or') }*/}və ya</div>
                    <div className="ml-3 flex-grow border-t border-gray-300" aria-hidden="true"></div>
                </div>
                <div className="pb-2 space-y-4">
                    <input
                        aria-invalid="true"
                        autoComplete="off"
                        id="email"
                        name="email"
                        placeholder="richard.hendricks@piedpiper.com"
                        type="text"
                        inputMode="text"
                        className="input"
                        aria-label="geremy@mailer.io"
                        autoCorrect="off"
                        autoCapitalize="none"
                        spellCheck="false"
                        value=""
                        onChange={changeEmailHandler} />
                    <div className="relative">
                        <input aria-invalid="true"
                        autoComplete="current-password"
                        id="password"
                        name="password"
                        placeholder="••••••••"
                        type="password"
                        className="input"
                        aria-label="Şifrə"
                        autoCapitalize="none"
                        spellCheck="false"
                        onChange={changePasswordHandler} />
                        <div v-if="type === 'password'">
                            <span className="iconify absolute translate-y-1/2 text-gray-400 top-0 my-3 mr-4 cursor-pointer right-0"
                                data-icon="mdi:eye-off"></span>
                        </div>
                        <div v-else-if="type !== 'password'" className="z-50">
                            <span className="iconify absolute translate-y-1/2 text-gray-400 top-0 my-3 mr-4 cursor-pointer right-0"
                                data-icon="mdi:eye"></span>
                        </div>
                    </div>
                    <div className="w-full">
                        {
                            loading
                            ?
                            <div className="border-cerulean-600 text-white rounded bg-cerulean-600 hover:opacity-90 mb-2 px-2 py-3">
                                <i className="mdi mdi-spin mdi-loading"/>
                            </div>
                            :
                            <button type="submit" className="btn w-full mx-auto block">
                            {/* {{ $t('devhub.login') }}     */}
                               Giriş
                            </button>
                        }
                    </div>
                </div>
                <div className="mt-4">
                    <Link className="block text-center text-sm text-cerulean-500" to="/">
                        {/* {{ $t('devhub.forgotPassword') }} */}
                        Şifrəni unutmusuz?
                    </Link>
                    <div className="mt-2 bg-white rounded py-4 text-sm border">
                        {/* {{ $t('devhub.notRegistered') }} */}
                        Hələ hesabınız yoxdur?
                        <Link to="/register" className="text-cerulean-500">
                            {/* {{ $t('devhub.register') }} */}
                            Qeydiyyatdan keçmək
                        </Link>
                    </div>
                </div>
            </form>
        </div>
    );
}

export default Login;
